apiVersion: v1
kind: Secret
metadata: 
  name: my-secret-2
stringData: 
  MYSQL_ROOT_PASSWORD: Pas5w0rd
  MYSQL_DATABASE: phonebook
  MYSQL_USER: talha-01
  MYSQL_PASSWORD: phonebook_123

# echo -n "password" | base64