apiVersion: v1
kind: Pod
metadata: 
  name: mysql
  labels: 
    app: mysql
spec: 
  containers: 
  - name: mysql
    image: mysql:5.7
    env: 
    - name: MYSQL_ROOT_PASSWORD
      valueFrom: 
        secretKeyRef: 
          name: my-secret-2
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: my-secret-2
          key: MYSQL_DATABASE
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: my-secret-2
          key: MYSQL_USER
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret-2
          key: MYSQL_PASSWORD
    ports: 
    - containerPort: 3306
    volumeMounts:
    - name: mysql-initdb
      mountPath: /docker-entrypoint-initdb.d
  volumes: 
  - name: mysql-initdb
    configMap: 
      name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE phone_book(id INT NOT NULL AUTO_INCREMENT, name VARCHAR(100) NOT NULL, number VARCHAR(100) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    INSERT INTO phone_book (name, number) VALUES ("John Doe", "1234567890");
    INSERT INTO phone_book (name, number) VALUES ("Jane Doe", "5558886589");